apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo-app
  namespace: devops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-demo

  template:
    metadata:
      labels:
        app: devops-demo

    spec:
      containers:
        - name: devops-demo

          image: 599657398123.dkr.ecr.ap-south-1.amazonaws.com/terraform-aws-devops-app:8f21a93ce578fa1df42e87ed1e32be85e1df982d

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 15
            periodSeconds: 20