apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: devops-demo-monitor
  namespace: devops-demo

spec:
  selector:
    matchLabels:
      app: devops-demo

  endpoints:
    - port: http
      path: /metrics
      interval: 15s