name: DevOps CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: terraform-aws-devops-app

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd app
          pytest -v


  security:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t terraform-aws-devops-app:test ./app

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: terraform-aws-devops-app:test
          severity: CRITICAL,HIGH
          exit-code: "1"
          ignore-unfixed: true